export type DocumentCategory = 
  | 'identity' 
  | 'license' 
  | 'passport' 
  | 'tax' 
  | 'health' 
  | 'utility' 
  | 'contract' 
  | 'other';

export type ShareMode = 'essential_text' | 'full_document';

export type SessionStatus = 
  | 'pending_donor_auth'     // Step 1 done: Receiver created Receiver Code, waiting for Donor to input & authorize
  | 'pending_receiver_entry' // Step 2-3 done: Donor authorized & generated Donor Code, waiting for Receiver to enter Donor Code
  | 'unlocked'               // Step 4 done: Receiver entered Donor Code, 10-minute access session active
  | 'expired'                // Session timer ran out
  | 'denied';                // Donor explicitly rejected

export interface DocumentItem {
  id: string;
  title: string;
  category: DocumentCategory;
  ownerName: string;
  documentNumber: string;
  issueDate: string;
  expiryDate: string;
  issuingAuthority: string;
  essentialFields: Record<string, string>;
  fileUrl?: string;
  fileName?: string;
  fileType?: string;
  fileSize?: string;
  notes?: string;
  createdAt: string;
  defaultShareMode: ShareMode;
}

export interface HandshakeSession {
  id: string;
  receiverName: string;
  receiverRole: string;
  receiverCode: string;           // 4-digit code generated by Receiver (2 min validity)
  receiverCodeCreatedAt: number;
  receiverCodeExpiresAt: number;
  donorCode?: string;             // 4-digit code generated by Donor upon approval (2 min validity)
  donorCodeCreatedAt?: number;
  donorCodeExpiresAt?: number;
  documentId: string;
  documentTitle: string;
  shareMode: ShareMode;
  status: SessionStatus;
  unlockedAt?: number;
  unlockedExpiresAt?: number;     // 10 minute countdown after unlock
  ipAddress: string;
}

export interface AuditLog {
  id: string;
  timestamp: string;
  receiverName: string;
  documentTitle: string;
  shareMode: ShareMode;
  action: 'REQUEST_GENERATED' | 'DONOR_AUTHORIZED' | 'HANDSHAKE_COMPLETED' | 'SESSION_EXPIRED' | 'ACCESS_DENIED';
  handshakeTx: string;
  ipAddress: string;
  details: string;
}

export interface ReceiverAccount {
  id: string;
  name: string;
  category: string;
  location: string;
  trustLevel: 'verified' | 'partner' | 'standard';
  iconName?: string;
}
